### PR TITLE
Fix Zeta::Rspec.run: Ensure infrastructure validation failure messages are displayed

### LINKED ISSUE #41: Refactor and fix rspec reporter
RSpec reporter does not work if 
```
 config.disable_monkey_patching!
````
is enabled. `RSpec` [here](https://github.com/moviepilot/lacerda/blob/master/lib/lacerda/reporters/rspec.rb#L6) is not calling rspec, but `Lacerda::Reporters::Rspec.describe`. This works because of RSpec's monkeypatching. If you'd disable monkeypatching and call `RSpec.describe`, you will get an error because you're inste an `it` block.

The reporter also depends on the `config.order = :random` not being set. If it's set, the errors are not displayed. I guess it's related with the previous thing.  With the current implementation it's a bit difficult to find a way to make this work.

### PR DESCRIPTION
**Pull request by ammancilla**
closes https://github.com/moviepilot/lacerda/issues/41

### CODE REVIEW

File: lib/zeta/rspec/autorun_all.rb [hunk 1]
```diff
@@ -1,33 +1,8 @@
...
-  # This is a bit odd. The RSpec reporter declares new describes inside. That
-  # fails usually in RSpec, but not in the way we're doing it.
-  # We need it because if this `it` would be a `context`, `contracts_fulfilled?`
-  # would be already evaluated before the previous examples run. This would
-  # make that this example fails, because the contracts have not been
-  # downloaded yet
-  it 'has a valid infrastructure' do
-    expect(Zeta.contracts_fulfilled?(Lacerda::Reporters::RSpec.new)).to eq true
-  end
-end
```
Comment (ammancilla) [inline lib/zeta/rspec/autorun_all.rb]: This code was a duplication of `Zeta::Rspec.run`

File: lib/zeta/rspec.rb [hunk 2]
```diff
@@ -1,27 +1,22 @@
...
-          Zeta.verbose = false
-          Zeta.update_contracts
-        }.to_not raise_error
-      end
+    # Update Contracts
+    Zeta.verbose = false
+    Zeta.update_contracts
 
-      it "validate infrastructure" do
-        expect(Zeta.contracts_fulfilled?(Lacerda::Reporters::RSpec.new)).to eq true
```
Comment (ammancilla) [inline lib/zeta/rspec.rb]: `Zeta.contracts_fulfilled?(Lacerda::Reporters::RSpec.new)` defines it owns test cases and expectations. By enclosing it in a `it`, and defining a new expectation `expect(Zeta.contracts_fulfilled?(Lacerda::Reporters::RSpec.new)).to eq(true)`, we are suppressing the error messages defined internally by zeta by the one returned by the new (eq(true)) expectation.

**Review by jayniz — APPROVED** [review]
