### PR TITLE
Fix RSpec test runner

### LINKED ISSUE #23: rspec helper is not fetching remote contracts
Zeta::RSpec.run fails, because it is only updating its own contracts.

```zeta-0.11.0/lib/zeta/rspec.rb:32``` change ```Zeta.update_own_contracts``` to ```Zeta.update_contracts```

### PR DESCRIPTION
**Pull request by thinkberg**
fixes #23

### CODE REVIEW

File: lib/zeta/rspec.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def self.update_contracts
   def self.run
     Zeta.verbose = false
     ensure_contracts_present
-    Zeta.update_own_contracts
+    Zeta.update_contracts
```
Comment (jayniz) [inline lib/zeta/rspec.rb]: Perhaps something like this would also work:

```ruby

  def self.run
    RSpec.describe "Update Zeta infrastructure once" do
      it "download infrastructure" do
        expect{
          Zeta.config
        }.to_not raise_error
      end

      it "download specifications" do
        expect{
          Zeta.update_contracts
        }.to_not raise_error
      end

      describe "validate infrastructure" do
        Zeta.verbose = false
        ensure_contracts_present
        Zeta.update_own_contracts
        Zeta.contracts_fulfilled?(Lacerda::Reporters::RSpec.new)
      end
    end
  end
```
